# Generated by Django 4.1.4 on 2023-02-04 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_order_orderstatus_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
            preserve_default=False,
        ),
    ]
